mqtt_broker:
  server: 127.0.0.1
  port: 1883

mailer:
  from_name: Daemon
  from_address: source@example.com
  to_address: destination@example.com
  subject: Daemon name
  smtp:
    server: 127.0.0.1
    port: 25

subscriptions:
  - topic: my/mqtt/topic1/+
  - topic: my/mqtt/topic2/+
    heartbeat_watchdog: true
  - topic: my/mqtt/topic3
    mail_alert: true
  - topic: my/mqtt/topic4
    metric:
      - type: gauge
        key: temperature
      - type: gauge
        key: humidity

prometheus:
       enabled: true
       http_port: 8000

ntp_service:
  enabled: true
  topic: ntp
